#!/usr/bin/env node
"use strict";

const
    SeatMap = require('./src/sessions/seatmap'),
    Sessions = require('./src/sessions/sessions'),
    Dates = require('./src/events/dates'),
    Movies = require('./src/movies/movies');

/**
 *
 * @param {string} movie
 * @param {string} date
 * @param {...string} session
 * @returns {void}
 */
async function main(movie, date, ...session) {
    try {
        // filter by movie
        const selectedMovie = await Movies.search(movie);
        if (!selectedMovie) {
            return;
        }

        // filter by date
        const selectedDate = await Dates.search(selectedMovie, date);
        if (!selectedDate) {
            return;
        }

        // filter by theater and session
        const selectedSession = await Sessions.search(selectedMovie, selectedDate, Array.from(session).join(''));
        if (!selectedSession) {
            return;
        }

        // if we got here, we have one and only one session; let's get its seat map
        const seatMapXml = await SeatMap.fetch(selectedSession);
        const seats = SeatMap.parseSeats(seatMapXml);
        if (seats) {
            SeatMap.show(seats);
        }

    } catch (error) {
        console.error(error);
    }
}

main(...process.argv.slice(2));
